---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - vars/main.yml
    - vars/phala.yml

  roles:
    - precheck
    - hardware-info
    - defaults
    - sgx-install
    - sgx-test

