---
    - name: "Update repository caches"
      apt: 
        update_cache=yes 
        force_apt_get=yes 
        cache_valid_time=3600

    - name: "Update all packages"
      apt:
        upgrade=dist
        force_apt_get=yes

    - name: "Install required tools and packages"
      apt:
        name:
          - build-essential
          - ocaml
          - ocamlbuild
          - automake
          - autoconf
          - libtool
          - wget
          - python
          - libssl-dev
          - libcurl4-openssl-dev
          - protobuf-compiler
          - libprotobuf-dev
          - sudo
          - kmod
          - vim
          - curl
          - git-core
          - libprotobuf-c0-dev
          - libboost-thread-dev
          - libboost-system-dev
          - liblog4cpp5-dev
          - libjsoncpp-dev
          - alien
          - uuid-dev
          - libxml2-dev
          - cmake
          - pkg-config
          - expect
          - systemd-sysv
          - gdb
          - jq
          - zip
          - unzip
        state: latest
        update_cache: yes

    - name: Check if a reboot is needed 
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot server if required for updates
      reboot:
        msg: "Reboot initiated by Ansible due to kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists


